# Generated by Django 5.2.9 on 2026-06-04 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('tab_name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sayfa Ziyareti',
                'verbose_name_plural': 'Sayfa Ziyaretleri',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PageViewSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('path', models.CharField(max_length=200)),
                ('tab_name', models.CharField(max_length=100)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ziyaret Özeti',
                'verbose_name_plural': 'Ziyaret Özetleri',
                'ordering': ['-date', '-visit_count'],
                'unique_together': {('date', 'path')},
            },
        ),
    ]
