# Generated by Django 5.2.9 on 2026-03-01 15:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliometricJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_format', models.CharField(blank=True, choices=[('bibtex', 'BibTeX (.bib)'), ('csv_wos', 'Web of Science CSV'), ('csv_scopus', 'Scopus CSV'), ('csv_auto', 'CSV (Otomatik)')], max_length=20)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('demo_pdf_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Demo PDF URL (S3)')),
                ('full_pdf_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Tam Rapor PDF URL (S3)')),
                ('demo_email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblio_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bibliometrik Analiz',
                'verbose_name_plural': 'Bibliometrik Analizler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BibliometricOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, default=150, max_digits=10, verbose_name='Toplam Tutar (TL)')),
                ('status', models.CharField(choices=[('pending_payment', 'Ödeme Bekleniyor'), ('payment_review', 'Ödeme İnceleniyor'), ('approved', 'Onaylandı'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı - Gönderildi'), ('cancelled', 'İptal')], default='pending_payment', max_length=20)),
                ('payment_note', models.TextField(blank=True, verbose_name='Ödeme Açıklaması')),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin Notu')),
                ('results_email_sent', models.BooleanField(default=False)),
                ('results_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bibliometrics.bibliometricjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblio_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bibliometrik Analiz Siparişi',
                'verbose_name_plural': 'Bibliometrik Analiz Siparişleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
