# Generated by Django 5.2.9 on 2026-03-01 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliometrics', '0001_initial'),
        ('openalex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliometricjob',
            name='alex_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biblio_jobs', to='openalex.alexsearchjob'),
        ),
        migrations.AddField(
            model_name='bibliometricjob',
            name='source',
            field=models.CharField(default='upload', max_length=20),
        ),
        migrations.AlterField(
            model_name='bibliometricjob',
            name='file_format',
            field=models.CharField(blank=True, choices=[('bibtex', 'BibTeX (.bib)'), ('csv_wos', 'Web of Science CSV'), ('csv_scopus', 'Scopus CSV'), ('csv_auto', 'CSV (Otomatik)'), ('openalex_json', 'OpenAlex (Otomatik)'), ('openalex_txt', 'OpenAlex TXT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bibliometricorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Toplam Tutar (TL)'),
        ),
    ]
