# Generated by Django 5.2.9 on 2026-03-12 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliometrics', '0002_add_source_alex_job'),
        ('openalex', '0002_alexorder_openalex_al_status_239dfe_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bibliometricjob',
            index=models.Index(fields=['status'], name='bibliometri_status_b0679b_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliometricjob',
            index=models.Index(fields=['created_at'], name='bibliometri_created_930a72_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliometricorder',
            index=models.Index(fields=['status'], name='bibliometri_status_5aff4c_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliometricorder',
            index=models.Index(fields=['created_at'], name='bibliometri_created_7c0ccb_idx'),
        ),
    ]
