# Generated by Django 5.2.9 on 2026-05-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliometrics', '0003_bibliometricjob_bibliometri_status_b0679b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliometricjob',
            name='file_format',
            field=models.CharField(blank=True, choices=[('bibtex', 'BibTeX (.bib)'), ('wos_txt', 'Web of Science Plain Text (ISI)'), ('csv_wos', 'Web of Science Tab-Delimited'), ('csv_scopus', 'Scopus CSV'), ('csv_auto', 'CSV (Otomatik)'), ('openalex_json', 'OpenAlex (Otomatik)'), ('openalex_txt', 'OpenAlex TXT')], max_length=20),
        ),
    ]
