# Generated by Django 5.2.17 on 2026-09-29 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliometrics', '0004_alter_bibliometricjob_file_format'),
        ('pubmed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliometricjob',
            name='pubmed_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biblio_jobs', to='pubmed.pubmedsearchjob'),
        ),
        migrations.AlterField(
            model_name='bibliometricjob',
            name='file_format',
            field=models.CharField(blank=True, choices=[('bibtex', 'BibTeX (.bib)'), ('wos_txt', 'Web of Science Plain Text (ISI)'), ('csv_wos', 'Web of Science Tab-Delimited'), ('csv_scopus', 'Scopus CSV'), ('csv_auto', 'CSV (Otomatik)'), ('openalex_json', 'OpenAlex (Otomatik)'), ('openalex_txt', 'OpenAlex TXT'), ('pubmed_json', 'PubMed (Otomatik)')], max_length=20),
        ),
    ]
