# Generated by Django 5.2.9 on 2026-03-12 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trdizin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dizinorder',
            index=models.Index(fields=['status'], name='trdizin_diz_status_2697c9_idx'),
        ),
        migrations.AddIndex(
            model_name='dizinorder',
            index=models.Index(fields=['created_at'], name='trdizin_diz_created_efd5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='dizinsearchjob',
            index=models.Index(fields=['status'], name='trdizin_diz_status_6da930_idx'),
        ),
        migrations.AddIndex(
            model_name='dizinsearchjob',
            index=models.Index(fields=['created_at'], name='trdizin_diz_created_e1e7a3_idx'),
        ),
    ]
