# Generated by Django 5.2.9 on 2026-03-12 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openalex', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alexorder',
            index=models.Index(fields=['status'], name='openalex_al_status_239dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='alexorder',
            index=models.Index(fields=['created_at'], name='openalex_al_created_278b35_idx'),
        ),
        migrations.AddIndex(
            model_name='alexsearchjob',
            index=models.Index(fields=['status'], name='openalex_al_status_967fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='alexsearchjob',
            index=models.Index(fields=['created_at'], name='openalex_al_created_b72a79_idx'),
        ),
    ]
