# Generated by Django 5.2.9 on 2026-06-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openalex', '0002_alexorder_openalex_al_status_239dfe_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlexOrderProxy',
            fields=[
            ],
            options={
                'verbose_name': 'OpenAlex Siparişi',
                'verbose_name_plural': 'OpenAlex Siparişleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('openalex.alexorder',),
        ),
    ]
