# Generated by Django 5.2.9 on 2026-01-18 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_quizquestion_quizscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='Hikaye Alıntısı')),
                ('achievements', models.JSONField(default=list, verbose_name='Başarı Maddeleri')),
                ('resources', models.JSONField(default=list, verbose_name='Kullanılan Kaynaklar')),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Haftanın Hikayesi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Başarı Hikayesi',
                'verbose_name_plural': 'Başarı Hikayeleri',
            },
        ),
    ]
