# Generated by Django 5.2.9 on 2026-01-18 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_freelancejob_jobproposal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancejob',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Beğenenler'),
        ),
        migrations.AddField(
            model_name='freelancejob',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Kaydedenler'),
        ),
    ]
