# Generated by Django 5.2.9 on 2026-01-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_freelancejob_likes_freelancejob_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancejob',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Görüntülenme'),
        ),
    ]
