# Generated by Django 5.2.9 on 2026-01-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_userquizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin_verified',
            field=models.BooleanField(default=False, verbose_name='LinkedIn Doğrulandı'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefon Numarası'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='Telefon Doğrulandı'),
        ),
    ]
