# Generated by Django 5.2.9 on 2026-01-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_profile_linkedin_verified_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='forum.profile', verbose_name='Takip Edilenler'),
        ),
    ]
