# Generated by Django 5.2.9 on 2026-01-22 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_profile_following'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCategoryScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('spss', 'SPSS'), ('python', 'Python'), ('r', 'R'), ('statistics', 'İstatistik'), ('methodology', 'Metodoloji')], max_length=20, verbose_name='Kategori')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Doğru Cevap')),
                ('total_answers', models.PositiveIntegerField(default=0, verbose_name='Toplam Cevap')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Puan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_category_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kategori Quiz Puanı',
                'verbose_name_plural': 'Kategori Quiz Puanları',
                'unique_together': {('user', 'category')},
            },
        ),
    ]
