# Generated by Django 5.2.9 on 2026-01-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_quizcategoryscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancejob',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AddField(
            model_name='freelancejob',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Öne Çıkarılmış'),
        ),
    ]
