# Generated by Django 5.2.9 on 2026-01-23 20:12

from django.db import migrations, models


def add_expires_at_if_not_exists(apps, schema_editor):
    # Bu sütunlar migration 0028'de AddField ile düzgün ekleniyor.
    # Prod hotfix olarak yazılmış bu fonksiyon artık no-op.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_quizcategoryscore'),
    ]

    operations = [
        migrations.RunPython(add_expires_at_if_not_exists, migrations.RunPython.noop),
    ]
