# Generated by Django 5.2.9 on 2026-01-23 20:12

from django.db import migrations, models


def add_expires_at_if_not_exists(apps, schema_editor):
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                    WHERE table_name='forum_freelancejob' AND column_name='expires_at') THEN
                    ALTER TABLE forum_freelancejob ADD COLUMN expires_at timestamp with time zone NULL;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                    WHERE table_name='forum_freelancejob' AND column_name='is_featured') THEN
                    ALTER TABLE forum_freelancejob ADD COLUMN is_featured boolean DEFAULT false NOT NULL;
                END IF;
            END $$;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_quizcategoryscore'),
    ]

    operations = [
        migrations.RunPython(add_expires_at_if_not_exists, migrations.RunPython.noop),
    ]
