# Generated by Django 5.2.9 on 2026-01-23 20:49

from django.db import migrations, models


def add_topic_if_not_exists(apps, schema_editor):
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                    WHERE table_name='forum_quizquestion' AND column_name='topic') THEN
                    ALTER TABLE forum_quizquestion ADD COLUMN topic varchar(50) DEFAULT '' NOT NULL;
                END IF;
            END $$;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0025_add_job_featured_and_expires'),
    ]

    operations = [
        migrations.RunPython(add_topic_if_not_exists, migrations.RunPython.noop),
    ]
