# Generated by Django 5.2.9 on 2026-01-23 20:49

from django.db import migrations, models


def add_topic_if_not_exists(apps, schema_editor):
    # Bu alan migration 0028'de AddField ile düzgün ekleniyor.
    # Prod hotfix olarak yazılmış bu fonksiyon artık no-op.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0025_add_job_featured_and_expires'),
    ]

    operations = [
        migrations.RunPython(add_topic_if_not_exists, migrations.RunPython.noop),
    ]
