# Generated by Django 5.2.9 on 2026-01-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0025_add_job_featured_and_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='topic',
            field=models.CharField(blank=True, max_length=50, verbose_name='Alt Konu'),
        ),
    ]
