# Generated by Django 5.2.9 on 2026-01-24 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def safe_add_columns(apps, schema_editor):
    # Bu fonksiyon artık gerekli değil - alanlar 0028'de ekleniyor
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0026_add_quiz_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(safe_add_columns, migrations.RunPython.noop),
        migrations.CreateModel(
            name='JobReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Puan')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Yorum')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Onaylandı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='forum.freelancejob')),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İş Değerlendirmesi',
                'verbose_name_plural': 'İş Değerlendirmeleri',
                'unique_together': {('job', 'reviewer')},
            },
        ),
    ]
