# Generated by Django 5.2.9 on 2026-01-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0027_add_job_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancejob',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AddField(
            model_name='freelancejob',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Öne Çıkarılmış'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='topic',
            field=models.CharField(blank=True, max_length=50, verbose_name='Alt Konu'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='category',
            field=models.CharField(choices=[('spss', 'SPSS'), ('python', 'Python'), ('r', 'R'), ('statistics', 'İstatistik'), ('methodology', 'Metodoloji')], max_length=50, verbose_name='Kategori'),
        ),
    ]
