# Generated by Django 5.2.9 on 2026-01-24 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0028_freelancejob_expires_at_freelancejob_is_featured_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Premium Bitiş Tarihi'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='İsim')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miktar (TL)')),
                ('payment_id', models.CharField(max_length=100, unique=True, verbose_name='Ödeme ID')),
                ('conversation_id', models.CharField(blank=True, max_length=100, verbose_name='Konuşma ID')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20, verbose_name='Durum')),
                ('premium_days_granted', models.IntegerField(default=0, verbose_name='Verilen Premium Gün')),
                ('message', models.TextField(blank=True, verbose_name='Mesaj')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anonim')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='Bağışçı')),
            ],
            options={
                'verbose_name': 'Bağış',
                'verbose_name_plural': 'Bağışlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
