# Generated by Django 5.2.9 on 2026-01-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0029_profile_premium_expires_at_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/%Y/%m/', verbose_name='Dosya Eki'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dosya Adı'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
