# Generated by Django 5.2.9 on 2026-01-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0030_add_attachment_to_privatemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Miktar (TL)')),
                ('premium_days', models.IntegerField(verbose_name='Premium Gün Sayısı')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Katman Adı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Bağış Katmanı',
                'verbose_name_plural': 'Bağış Katmanları',
                'ordering': ['-min_amount'],
            },
        ),
    ]
