# Generated by Django 5.2.9 on 2026-01-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0032_populate_donation_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancejob',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vitrin Bitiş Tarihi'),
        ),
    ]
