# Generated by Django 5.2.9 on 2026-01-26 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0033_freelancejob_featured_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('payment_id', models.CharField(max_length=100, unique=True, verbose_name='Ödeme ID')),
                ('conversation_id', models.CharField(max_length=100, verbose_name='Konuşma ID')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('success', 'Başarılı'), ('failed', 'Başarısız')], default='pending', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='forum.freelancejob', verbose_name='İlan')),
            ],
        ),
    ]
