# Generated by Django 5.2.9 on 2026-01-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0034_jobpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancejob',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Referans Numarası'),
        ),
        migrations.AlterField(
            model_name='jobpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('pending_confirmation', 'Onay Bekliyor'), ('success', 'Başarılı'), ('failed', 'Başarısız')], default='pending', max_length=20, verbose_name='Durum'),
        ),
    ]
