# Generated by Django 5.2.9 on 2026-01-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0035_freelancejob_reference_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Etiket Adı')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='bi-tag', max_length=50, verbose_name='İkon')),
                ('color', models.CharField(default='#6366f1', max_length=20, verbose_name='Renk')),
                ('tag_type', models.CharField(choices=[('software', 'Yazılım'), ('status', 'Durum'), ('other', 'Diğer')], default='software', max_length=20, verbose_name='Etiket Türü')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Konu Etiketi',
                'verbose_name_plural': 'Konu Etiketleri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='topics', to='forum.topictag', verbose_name='Etiketler'),
        ),
    ]
