# Generated by Django 5.2.9 on 2026-01-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0037_populate_tags_and_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_access_token', models.TextField(blank=True, verbose_name='LinkedIn Access Token')),
                ('linkedin_person_urn', models.CharField(blank=True, max_length=100, verbose_name='LinkedIn Person URN')),
                ('linkedin_connected_at', models.DateTimeField(blank=True, null=True, verbose_name='LinkedIn Bağlantı Tarihi')),
                ('auto_share_topics', models.BooleanField(default=False, verbose_name='Yeni konuları otomatik paylaş')),
                ('auto_share_jobs', models.BooleanField(default=False, verbose_name='Yeni ilanları otomatik paylaş')),
            ],
            options={
                'verbose_name': 'Site Ayarı',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
