# Generated by Django 5.2.9 on 2026-01-30 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0038_add_site_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='bi-folder', max_length=50, verbose_name='İkon')),
                ('color', models.CharField(default='#00d2ff', max_length=20, verbose_name='Renk')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Blog Kategorisi',
                'verbose_name_plural': 'Blog Kategorileri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('excerpt', models.TextField(help_text='Kısa açıklama (liste görünümünde gösterilir)', max_length=300, verbose_name='Özet')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/', verbose_name='Kapak Görseli')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayında')], default='draft', max_length=10, verbose_name='Durum')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='SEO Başlık')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='SEO Açıklama')),
                ('shared_to_linkedin', models.BooleanField(default=False, verbose_name="LinkedIn'e Paylaşıldı")),
                ('linkedin_share_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Yayın Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='forum.blogcategory', verbose_name='Kategori')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='Beğeniler')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
