# Generated by Django 5.2.9 on 2026-01-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0039_add_blog_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_organization_id',
            field=models.CharField(blank=True, help_text="Şirket sayfası URL'sindeki numara (örn: 101597284)", max_length=50, verbose_name='LinkedIn Şirket ID'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Maksimum 50.000 karakter (~8.000 kelime)', verbose_name='İçerik'),
        ),
    ]
