# Generated by Django 5.2.9 on 2026-01-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0040_add_linkedin_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancejob',
            name='feature_status',
            field=models.CharField(choices=[('none', 'Yok'), ('pending', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='none', max_length=20, verbose_name='Vitrin Durumu'),
        ),
    ]
