# Generated by Django 5.2.9 on 2026-01-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0041_add_feature_status_to_freelancejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='can_write_blog',
            field=models.BooleanField(default=False, verbose_name='Blog Yazabilir'),
        ),
    ]
