# Generated by Django 5.2.9 on 2026-01-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0042_add_can_write_blog_to_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpayment',
            name='duration_days',
            field=models.PositiveIntegerField(default=7, verbose_name='Vitrin Süresi (Gün)'),
        ),
    ]
