# Generated by Django 5.2.9 on 2026-02-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0043_add_duration_days_to_jobpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='edu_proposal_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='EDU Teklif Hakkı Bitiş'),
        ),
    ]
