# Generated by Django 5.2.9 on 2026-02-05 20:58

import forum.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0046_cleanup_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=forum.storage.get_storage, upload_to='blog/covers/', verbose_name='Kapak Görseli'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=forum.storage.get_storage, upload_to='chat_attachments/%Y/%m/', verbose_name='Dosya Eki'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=forum.storage.get_storage, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=forum.storage.get_storage, upload_to='covers/', verbose_name='Kapak Fotoğrafı'),
        ),
    ]
