# Generated by Django 5.2.9 on 2026-02-06 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0047_alter_blogpost_cover_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20, verbose_name='Onay Durumu'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='success_stories', to='forum.freelancejob', verbose_name='İlgili İş İlanı'),
        ),
        migrations.AlterUniqueTogether(
            name='successstory',
            unique_together={('user', 'job')},
        ),
    ]
