# Generated by Django 5.2.9 on 2026-02-06 21:22

from django.db import migrations


def set_existing_approved(apps, schema_editor):
    SuccessStory = apps.get_model('forum', 'SuccessStory')
    SuccessStory.objects.filter(approval_status='pending').update(approval_status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0048_successstory_job_approval'),
    ]

    operations = [
        migrations.RunPython(set_existing_approved, migrations.RunPython.noop),
    ]
