# Generated by Django 5.2.9 on 2026-02-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0049_set_existing_stories_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='linkedin_access_token',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='linkedin_connected_at',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='linkedin_organization_id',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='linkedin_person_urn',
        ),
    ]
