# Generated by Django 5.2.9 on 2026-02-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0050_remove_linkedin_and_buffer_api_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feature_ai_assistant',
            field=models.BooleanField(default=True, verbose_name='AI Asistan'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_blog',
            field=models.BooleanField(default=True, verbose_name='Blog'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_donation',
            field=models.BooleanField(default=True, verbose_name='Bağış Sistemi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_market',
            field=models.BooleanField(default=True, verbose_name='Hizmetler Pazarı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_messaging',
            field=models.BooleanField(default=True, verbose_name='Özel Mesajlaşma'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_quiz',
            field=models.BooleanField(default=True, verbose_name='İstatistik Arena (Quiz)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_success_stories',
            field=models.BooleanField(default=True, verbose_name='Başarı Hikayeleri'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_yoktez',
            field=models.BooleanField(default=True, verbose_name='YÖK Tez Tarama'),
        ),
    ]
