# Generated by Django 5.2.9 on 2026-02-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0051_sitesettings_feature_ai_assistant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Okundu'),
        ),
    ]
