# Generated by Django 5.2.9 on 2026-02-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0052_add_is_read_to_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feature_trdizin_scraper',
            field=models.BooleanField(default=True, verbose_name='TR Dizin Tarama'),
        ),
    ]
