# Generated by Django 5.2.9 on 2026-02-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0053_sitesettings_feature_trdizin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feature_openalex',
            field=models.BooleanField(default=True, verbose_name='OpenAlex Yayın Tarama'),
        ),
    ]
