# Generated by Django 5.2.9 on 2026-02-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0054_sitesettings_feature_openalex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='feature_yoktez',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='feature_trdizin',
            field=models.BooleanField(default=False, verbose_name='TR Dizin Tarama'),
        ),
    ]
