# Generated by Django 5.2.9 on 2026-02-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0055_remove_feature_yoktez_trdizin_default_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feature_oaipmh',
            field=models.BooleanField(default=True, verbose_name='Üniversite Tez Arşivi (OAI-PMH)'),
        ),
    ]
