# Generated by Django 5.2.9 on 2026-03-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0056_add_feature_oaipmh'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feature_bibliometrics',
            field=models.BooleanField(default=True, verbose_name='Bibliometrik Analiz'),
        ),
    ]
