# Generated by Django 5.2.9 on 2026-03-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0057_add_feature_bibliometrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='biblio_price_2000',
            field=models.PositiveIntegerField(default=900, verbose_name='501-2000 kayıt fiyatı (TL)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='biblio_price_3000',
            field=models.PositiveIntegerField(default=1300, verbose_name='2001-3000 kayıt fiyatı (TL)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='biblio_price_4000',
            field=models.PositiveIntegerField(default=1700, verbose_name='3001-4000 kayıt fiyatı (TL)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='biblio_price_500',
            field=models.PositiveIntegerField(default=500, verbose_name='0-500 kayıt fiyatı (TL)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='biblio_price_5000',
            field=models.PositiveIntegerField(default=2100, verbose_name='4001-5000 kayıt fiyatı (TL)'),
        ),
    ]
