# Generated by Django 5.2.9 on 2026-03-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0058_sitesettings_biblio_price_2000_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feature_yoktez',
            field=models.BooleanField(default=True, verbose_name='YÖK Tez Arama'),
        ),
    ]
