# Generated by Django 5.2.9 on 2026-03-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0059_sitesettings_feature_yoktez'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feature_tezanaliz',
            field=models.BooleanField(default=True, verbose_name='Tez & Makale Analizi'),
        ),
    ]
