# Generated by Django 5.2.9 on 2026-03-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0060_feature_tezanaliz'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='analiz_max_records',
            field=models.PositiveIntegerField(default=500, help_text='Tez & Makale Analizi ve TR Dizin Makale Analizi için işlenecek maksimum kayıt sayısı. (default: 500)', verbose_name='Analiz Maks. Kayıt Sayısı'),
        ),
    ]
