# Generated by Django 5.2.9 on 2026-03-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0061_sitesettings_analiz_max_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='scrap_max_records',
            field=models.PositiveIntegerField(default=5000, help_text='TR Dizin, OpenAlex ve OAI-PMH scraperlarının çekebileceği maksimum kayıt sayısı. (default: 5000)', verbose_name='Scraping Maks. Kayıt Sayısı'),
        ),
    ]
