# Generated by Django 5.2.9 on 2026-03-13 20:53

import django.db.models.deletion
import forum.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0062_add_scrap_max_records'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Oda Başlığı')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('goal', models.TextField(max_length=500, verbose_name='Hedef')),
                ('ends_at', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('max_members', models.PositiveIntegerField(default=30, verbose_name='Maksimum Üye')),
                ('is_public', models.BooleanField(default=True, verbose_name='Herkese Açık')),
                ('status', models.CharField(choices=[('pending', 'Onay Bekliyor'), ('active', 'Aktif'), ('archived', 'Arşiv'), ('rejected', 'Reddedildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('terms_agreed', models.BooleanField(default=False, verbose_name='Şartname Onaylandı')),
                ('terms_agreed_at', models.DateTimeField(blank=True, null=True, verbose_name='Şartname Onay Tarihi')),
                ('review_note', models.TextField(blank=True, verbose_name='İnceleme Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_rooms', to='forum.category', verbose_name='İlgili Kategori')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Kurucu')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rooms', to=settings.AUTH_USER_MODEL, verbose_name='İnceleyen')),
            ],
            options={
                'verbose_name': 'Çalışma Odası',
                'verbose_name_plural': 'Çalışma Odaları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyRoomPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('file', models.FileField(blank=True, null=True, storage=forum.storage.get_storage, upload_to='studyrooms/', verbose_name='Dosya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_posts', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_posts', to='forum.studyroom')),
            ],
            options={
                'verbose_name': 'Oda Gönderisi',
                'verbose_name_plural': 'Oda Gönderileri',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyRoomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('creator', 'Kurucu'), ('member', 'Üye')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='forum.studyroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oda Üyeliği',
                'verbose_name_plural': 'Oda Üyelikleri',
                'unique_together': {('room', 'user')},
            },
        ),
    ]
