# Generated by Django 5.2.9 on 2026-03-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0063_studyroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroom',
            name='creator_bio',
            field=models.CharField(blank=True, max_length=300, verbose_name='Kurucu Tanıtımı'),
        ),
        migrations.AlterField(
            model_name='studyroom',
            name='max_members',
            field=models.PositiveIntegerField(default=20, verbose_name='Maksimum Üye'),
        ),
    ]
