# Generated by Django 5.2.9 on 2026-03-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0064_studyroom_creator_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feature_istatistik',
            field=models.BooleanField(default=True, verbose_name='İstatistik Analiz Araçları'),
        ),
    ]
