# Generated by Django 5.2.9 on 2026-04-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0065_feature_istatistik'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feature_proposal_price_privacy',
            field=models.BooleanField(default=True, help_text='İlan detaylarında teklif fiyatı yalnızca ilan sahibi ve teklif veren tarafından gösterilsin.', verbose_name='Teklif Fiyatı Gizliliği'),
        ),
    ]
