# Generated by Django 5.2.9 on 2026-04-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0066_sitesettings_feature_proposal_price_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='Onboarding Tamamlandı'),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_interests',
            field=models.JSONField(blank=True, default=list, verbose_name='İlgi Alanları'),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_tools',
            field=models.JSONField(blank=True, default=list, verbose_name='Kullanılan Araçlar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='segment',
            field=models.CharField(blank=True, choices=[('student', 'Öğrenci'), ('academic', 'Akademisyen'), ('expert', 'Uzman'), ('curious', 'Meraklı')], default='', max_length=20, verbose_name='Segment'),
        ),
    ]
