# Generated by Django 5.2.9 on 2026-04-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0067_profile_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login_streak_date',
            field=models.DateField(blank=True, null=True, verbose_name='Son Seri Güncellemesi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='login_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Giriş Serisi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_login_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='En Uzun Giriş Serisi'),
        ),
    ]
