# Generated by Django 5.2.9 on 2026-04-21 17:20

import forum.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0068_profile_login_streak'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim Soyisim')),
                ('title', models.CharField(max_length=100, verbose_name='Ünvan/Görev')),
                ('bio', models.TextField(verbose_name='Kısa Özgeçmiş')),
                ('image', models.ImageField(blank=True, null=True, storage=forum.storage.get_storage, upload_to='team/', verbose_name='Fotoğraf')),
                ('skills', models.CharField(blank=True, help_text='Virgülle ayırarak yazın (örn: SPSS, R Studio, Ölçek Geliştirme)', max_length=200, verbose_name='Yetenekler/Etiketler')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Ekip Üyesi',
                'verbose_name_plural': 'Ekip Üyeleri',
                'ordering': ['order'],
            },
        ),
    ]
