# Generated by Django 5.2.9 on 2026-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0069_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz/images/', verbose_name='Görsel (opsiyonel)'),
        ),
        migrations.AlterField(
            model_name='quizcategoryscore',
            name='category',
            field=models.CharField(choices=[('spss', 'SPSS'), ('python', 'Python'), ('r', 'R'), ('statistics', 'İstatistik'), ('methodology', 'Metodoloji'), ('cronbach', 'Güvenilirlik (Cronbach Alpha)'), ('normallik', 'Normallik Testi'), ('korelasyon', 'Korelasyon'), ('ttesti', 't-Testi'), ('anova', 'ANOVA'), ('betimsel', 'Betimleyici İstatistik'), ('output_reading', 'Çıktı Okuma')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='category',
            field=models.CharField(choices=[('spss', 'SPSS'), ('python', 'Python'), ('r', 'R'), ('statistics', 'İstatistik'), ('methodology', 'Metodoloji'), ('cronbach', 'Güvenilirlik (Cronbach Alpha)'), ('normallik', 'Normallik Testi'), ('korelasyon', 'Korelasyon'), ('ttesti', 't-Testi'), ('anova', 'ANOVA'), ('betimsel', 'Betimleyici İstatistik'), ('output_reading', 'Çıktı Okuma')], max_length=50, verbose_name='Kategori'),
        ),
    ]
