# Generated by Django 5.2.9 on 2026-04-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0070_quiz_add_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancejob',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Düzenlendi'),
        ),
    ]
