# Generated by Django 5.2.9 on 2026-04-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0071_add_freelancejob_is_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Etiket Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Blog Etiketi',
                'verbose_name_plural': 'Blog Etiketleri',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Başlangıç'), ('intermediate', 'Orta'), ('advanced', 'İleri')], help_text='Hedef okuyucu kitlesi (boş bırakılabilir)', max_length=15, verbose_name='Seviye'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='forum.blogtag', verbose_name='Etiketler'),
        ),
    ]
