# Generated by Django 5.2.9 on 2026-05-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0073_seed_initial_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancejob',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min Bütçe (TL)'),
        ),
    ]
