# Generated by Django 5.2.9 on 2026-05-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0074_freelancejob_budget_min_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancejob',
            name='expected_duration',
            field=models.CharField(blank=True, max_length=100, verbose_name='Beklenen Teslim Süresi'),
        ),
    ]
