# Generated by Django 5.2.9 on 2026-05-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0116_blog_veri_kazima_linkler_guncelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
