# Generated by Django 5.2.9 on 2026-05-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0118_site_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feature_semanticscholar',
            field=models.BooleanField(default=True, verbose_name='Semantic Scholar Tarama'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
