# Generated by Django 5.2.14 on 2026-05-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0118_site_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
