# Generated by Django 5.2.14 on 2026-05-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0119_alter_sitevisit_id'),
        ('forum', '0119_sitesettings_feature_semanticscholar_and_more'),
    ]

    operations = [
    ]
