# Generated by Django 5.2.14 on 2026-06-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0120_merge_20260530_2123'),
        ('forum', '0120_studyroompost_edited_at'),
    ]

    operations = [
    ]
