# Generated by Django 5.2.9 on 2026-06-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0121_merge_20260601_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('pending_confirmation', 'Onay Bekliyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20, verbose_name='Durum'),
        ),
    ]
