# Generated by Django 5.2.9 on 2026-06-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0122_donation_pending_confirmation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Şirket / Kurum')),
                ('analysis_type', models.CharField(choices=[('visualization', 'Veri Görselleştirme'), ('ml', 'Makine Öğrenmesi / Yapay Zeka'), ('statistics', 'İstatistiksel Analiz'), ('cleaning', 'Veri Temizleme / Hazırlama'), ('timeseries', 'Zaman Serisi Analizi'), ('nlp', 'Metin / NLP Analizi'), ('other', 'Diğer')], max_length=30, verbose_name='Analiz Türü')),
                ('description', models.TextField(verbose_name='Proje Açıklaması')),
                ('data_size', models.CharField(choices=[('small', '1.000 satırdan az'), ('medium', '1.000 – 100.000 satır'), ('large', '100.000 satır ve üzeri'), ('unknown', 'Bilmiyorum')], max_length=20, verbose_name='Veri Boyutu')),
                ('timeline', models.CharField(choices=[('urgent', '1 hafta içinde'), ('short', '1 ay içinde'), ('flexible', 'Esnek')], max_length=20, verbose_name='Süre Beklentisi')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('in_review', 'İnceleniyor'), ('contacted', 'İletişime Geçildi'), ('closed', 'Kapatıldı')], default='new', max_length=20, verbose_name='Durum')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notları')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proje Talebi',
                'verbose_name_plural': 'Proje Talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
