# Generated by Django 5.2.9 on 2026-06-06 22:39

import django.db.models.deletion
from django.db import migrations, models


def clear_old_categories(apps, schema_editor):
    FreelanceJob = apps.get_model('forum', 'FreelanceJob')
    FreelanceJob.objects.all().update(category=None)


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0123_add_project_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'İş Kategorisi',
                'verbose_name_plural': 'İş Kategorileri',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.RunPython(clear_old_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='freelancejob',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='forum.jobcategory', verbose_name='Kategori'),
        ),
    ]
