# Generated by Django 5.2.9 on 2026-06-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0124_job_category_independent'),
    ]

    operations = [
        # Eski Skill M2M verisi JobCategory ile uyumsuz — önce temizle
        migrations.RunSQL(
            sql="DELETE FROM forum_profile_skills;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='forum.jobcategory', verbose_name='Uzmanlık Alanları'),
        ),
    ]
