# Generated by Django 5.2.9 on 2026-06-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0125_profile_skills_to_jobcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='source',
            field=models.CharField(blank=True, choices=[('direct', 'Doğrudan Form'), ('yoktez', 'YÖK Tez'), ('trdizin', 'TR Dizin')], default='direct', max_length=20, verbose_name='Kaynak'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='analysis_type',
            field=models.CharField(choices=[('visualization', 'Veri Görselleştirme'), ('ml', 'Makine Öğrenmesi / Yapay Zeka'), ('statistics', 'İstatistiksel Analiz'), ('cleaning', 'Veri Temizleme / Hazırlama'), ('timeseries', 'Zaman Serisi Analizi'), ('nlp', 'Metin / NLP Analizi'), ('literature', 'Tez / Makale Veri İndirme'), ('other', 'Diğer')], max_length=30, verbose_name='Analiz Türü'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kişi / Şirket / Kurum'),
        ),
    ]
