# Generated by Django 5.2.9 on 2026-06-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0126_projectrequest_source_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silme Talebi Tarihi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='deletion_token',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Silme Token'),
        ),
        migrations.AddField(
            model_name='profile',
            name='deletion_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token Geçerlilik Süresi'),
        ),
    ]
