# Generated by Django 5.2.9 on 2026-06-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0127_profile_account_deletion_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='source',
            field=models.CharField(blank=True, choices=[('direct', 'Doğrudan Form'), ('yoktez', 'YÖK Tez'), ('trdizin', 'TR Dizin'), ('tool', 'Analiz Aracı')], default='direct', max_length=20, verbose_name='Kaynak'),
        ),
    ]
