# Generated by Django 5.2.9 on 2026-06-15 13:14

from django.db import migrations
from django.db.models import F


def set_published_at(apps, schema_editor):
    BlogPost = apps.get_model('forum', 'BlogPost')
    updated = BlogPost.objects.filter(
        status='published', published_at__isnull=True
    ).update(published_at=F('created_at'))
    print(f"  {updated} blog yazısına published_at atandı.")


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0128_projectrequest_source_tool'),
    ]

    operations = [
        migrations.RunPython(set_published_at, migrations.RunPython.noop),
    ]
