# Generated by Django 5.2.13 on 2026-07-03 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0140_patch_last2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Davet Kodu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Davet Kodu',
                'verbose_name_plural': 'Davet Kodları',
            },
        ),
        migrations.CreateModel(
            name='ReferralUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='E-posta Doğrulama Tarihi')),
                ('qualified_at', models.DateTimeField(blank=True, null=True, verbose_name='Koşul Sağlanma Tarihi')),
                ('rewarded', models.BooleanField(default=False, verbose_name='Ödüllendirildi')),
                ('flagged', models.BooleanField(default=False, verbose_name='Şüpheli (Ödülsüz)')),
                ('premium_days_awarded', models.PositiveIntegerField(default=0, verbose_name='Verilen Premium Gün')),
                ('reputation_awarded', models.PositiveIntegerField(default=0, verbose_name='Verilen Reputation')),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL, verbose_name='Davet Edilen')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL, verbose_name='Davet Eden')),
            ],
            options={
                'verbose_name': 'Davet Kullanımı',
                'verbose_name_plural': 'Davet Kullanımları',
            },
        ),
    ]
