# Generated by Django 5.2.16 on 2026-07-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0141_referral_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feature_transcript',
            field=models.BooleanField(default=True, verbose_name='YouTube Transcript İndirici'),
        ),
    ]
