# Generated by Django 5.2.16 on 2026-07-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0142_sitesettings_feature_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='feature_transcript',
            field=models.BooleanField(default=False, help_text="Cloud provider IP'leri (Hetzner, Render vb.) YouTube tarafından engelleniyor — sunucuda çalışmıyor, sadece lokal ortamda test edilebilir. Bkz. analizus.md §26.", verbose_name='YouTube Transcript İndirici'),
        ),
    ]
