# Generated by Django 5.2.9 on 2026-07-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0143_alter_sitesettings_feature_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='analysis_type',
            field=models.CharField(choices=[('visualization', 'Veri Görselleştirme'), ('ml', 'Makine Öğrenmesi / Yapay Zeka'), ('statistics', 'İstatistiksel Analiz'), ('cleaning', 'Veri Temizleme / Hazırlama'), ('timeseries', 'Zaman Serisi Analizi'), ('nlp', 'Metin / NLP Analizi'), ('literature', 'Tez / Makale Veri İndirme'), ('verification', 'AI Analiz Doğrulama'), ('other', 'Diğer')], max_length=30, verbose_name='Analiz Türü'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='source',
            field=models.CharField(blank=True, choices=[('direct', 'Doğrudan Form'), ('yoktez', 'YÖK Tez'), ('trdizin', 'TR Dizin'), ('tool', 'Analiz Aracı'), ('hero', 'Ana Sayfa Hero'), ('home_corporate', 'Ana Sayfa Kurumsal'), ('verification', 'AI Doğrulama Bandı')], default='direct', max_length=20, verbose_name='Kaynak'),
        ),
    ]
