# Generated by Django 5.2.9 on 2026-07-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0145_sitesettings_feature_agentic_landing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='source',
            field=models.CharField(blank=True, choices=[('direct', 'Doğrudan Form'), ('yoktez', 'YÖK Tez'), ('trdizin', 'TR Dizin'), ('tool', 'Analiz Aracı'), ('hero', 'Ana Sayfa Hero'), ('home_corporate', 'Ana Sayfa Kurumsal'), ('verification', 'AI Doğrulama Bandı'), ('agentic', 'AI Çözümler Sayfası'), ('tableau', 'Tableau Sayfası'), ('bibliometrics', 'Bibliometri Sayfası')], default='direct', max_length=20, verbose_name='Kaynak'),
        ),
    ]
