# Generated by Django 5.2.9 on 2026-07-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0146_projectrequest_source_tableau_bibliometrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='analysis_type',
            field=models.CharField(choices=[('visualization', 'Veri Görselleştirme'), ('ml', 'Makine Öğrenmesi / Yapay Zeka'), ('statistics', 'İstatistiksel Analiz'), ('cleaning', 'Veri Temizleme / Hazırlama'), ('timeseries', 'Zaman Serisi Analizi'), ('nlp', 'Metin / NLP Analizi'), ('literature', 'Tez / Makale Veri İndirme'), ('verification', 'AI Analiz Doğrulama'), ('agentic', 'AI Ajan / Otomasyon Projesi'), ('bibliometric', 'Bibliyometrik Analiz'), ('other', 'Diğer')], max_length=30, verbose_name='Analiz Türü'),
        ),
    ]
