# Generated by Django 5.2.9 on 2026-07-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0148_studyroomwaitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroom',
            name='room_type',
            field=models.CharField(choices=[('study', 'Çalışma Grubu'), ('project', 'Proje Odası'), ('thesis', 'Tez Danışmanlığı')], default='study', max_length=10, verbose_name='Oda Tipi'),
        ),
    ]
