# Generated by Django 5.2.16 on 2026-07-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0149_studyroom_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stat_min_display',
            field=models.PositiveIntegerField(default=25, help_text="Ana sayfa istatistik şeridinde bu değerin altındaki sayaçlar hiç gösterilmez (ör. '1 Açık İlan' yerine gizlenir). Eşik üstü sayaç sayısı 2'den azsa şerit tamamen gizlenir.", verbose_name='Sayaç Minimum Gösterim Eşiği'),
        ),
    ]
