# Generated by Django 5.2.16 on 2026-07-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0150_sitesettings_stat_min_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feature_training',
            field=models.BooleanField(default=False, verbose_name='Eğitim Hizmetleri Sayfası'),
        ),
    ]
