# Generated by Django 5.2.16 on 2026-07-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0151_add_feature_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='Kurum / Şirket')),
                ('request_type', models.CharField(choices=[('individual', 'Bireysel'), ('corporate', 'Kurumsal')], max_length=20, verbose_name='Talep Türü')),
                ('topic', models.CharField(blank=True, max_length=100, verbose_name="Eğitim Konusu (katalog slug'ı)")),
                ('other_topic', models.CharField(blank=True, max_length=150, verbose_name='Diğer Konu')),
                ('level', models.CharField(choices=[('beginner', 'Başlangıç'), ('intermediate', 'Orta'), ('advanced', 'İleri'), ('unknown', 'Emin değilim')], max_length=20, verbose_name='Seviye')),
                ('training_format', models.CharField(choices=[('online_live', 'Online canlı'), ('onsite', 'Yerinde'), ('hybrid', 'Hibrit'), ('flexible', 'Farketmez')], max_length=20, verbose_name='Format')),
                ('participants', models.CharField(choices=[('1', '1 kişi'), ('2-5', '2-5 kişi'), ('6-15', '6-15 kişi'), ('16+', '16+ kişi')], max_length=10, verbose_name='Katılımcı Sayısı')),
                ('timeline', models.CharField(choices=[('urgent', '2 hafta içinde'), ('month', '1 ay içinde'), ('flexible', 'Esnek')], max_length=20, verbose_name='Süre Beklentisi')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('kvkk_consent', models.BooleanField(default=False, verbose_name='KVKK Onayı')),
                ('source', models.CharField(blank=True, choices=[('egitim_hero', 'Eğitim Sayfası Hero'), ('egitim_kurs', 'Eğitim Kurs Kartı'), ('home', 'Ana Sayfa'), ('navbar', 'Navbar'), ('analiz_araci', 'Analiz Aracı'), ('direct', 'Doğrudan Form')], default='direct', max_length=20, verbose_name='Kaynak')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('in_review', 'İncelemede'), ('contacted', 'İletişime Geçildi'), ('scheduled', 'Planlandı'), ('closed', 'Kapandı')], default='new', max_length=20, verbose_name='Durum')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notları')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Eğitim Talebi',
                'verbose_name_plural': 'Eğitim Talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
