# Generated by Django 5.2.16 on 2026-09-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0152_add_training_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feature_multilingual',
            field=models.BooleanField(default=False, help_text="Kapalıyken navbar'daki dil seçici gizlenir ve /en/, /de/ URL'leri 404 döner. Kapsam: ana sayfa, navbar/footer, kayıt/giriş, proje talebi/danışmanlık/eğitim, makale analizi, OpenAlex, Semantic Scholar, istatistik araçları.", verbose_name='Çok Dilli Yayın (EN/DE)'),
        ),
    ]
