# Generated by Django 5.2.16 on 2026-09-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0153_sitesettings_feature_multilingual'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English'), ('de', 'Deutsch')], default='tr', max_length=5, verbose_name='Tercih Edilen Dil (e-postalar)'),
        ),
    ]
