# Generated by Django 5.2.16 on 2026-09-26 17:46

from django.db import migrations, models


# Mevcut rozetlerin EN/DE karşılıkları (slug → (name_en, desc_en, name_de, desc_de)).
# Yalnızca boş alanlar doldurulur; admin'den girilmiş çeviri ezilmez.
# Listede olmayan slug'lar Türkçe asıl alana düşer (Badge.localized_*).
BADGE_TRANSLATIONS = {
    'efsane': ('Legend', 'Earned 10,000 academic points – ALL PERMISSIONS',
               'Legende', '10.000 akademische Punkte erreicht – ALLE BERECHTIGUNGEN'),
    'profesor': ('Professor', 'Earned 5,000 academic points',
                 'Professor/in', '5.000 akademische Punkte erreicht'),
    'uzman': ('Expert', 'Earned 2,500 academic points – CAN SUBMIT PROPOSALS',
              'Experte/Expertin', '2.500 akademische Punkte erreicht – DARF ANGEBOTE ABGEBEN'),
    'bilgi-kaynagi': ('Knowledge Source', 'Earned 1,000 academic points',
                      'Wissensquelle', '1.000 akademische Punkte erreicht'),
    'aktif-katilimci': ('Active Participant', 'Earned 500 academic points',
                        'Aktive Teilnahme', '500 akademische Punkte erreicht'),
    'yukselen-yildiz': ('Rising Star', 'Earned 100 academic points',
                        'Aufsteigender Stern', '100 akademische Punkte erreicht'),
    'konu-acici': ('Topic Starter', 'Started 20 topics',
                   'Themenstarter/in', '20 Themen eröffnet'),
    'en-iyi-cevap': ('Best Answer', 'Had an answer selected as "Most Helpful"',
                     'Beste Antwort', 'Eine Antwort wurde als „Hilfreichste“ ausgewählt'),
    'cozum-ustasi': ('Solution Master', 'Received "Most Helpful Answer" 25 times – CAN SUBMIT PROPOSALS',
                     'Lösungsprofi', '25-mal „Hilfreichste Antwort“ erhalten – DARF ANGEBOTE ABGEBEN'),
    'yardimsever': ('Helpful', 'Answered 50 questions',
                    'Hilfsbereit', '50 Fragen beantwortet'),
    'moderator': ('Moderator', 'Forum moderator – ALL PERMISSIONS',
                  'Moderator/in', 'Forum-Moderation – ALLE BERECHTIGUNGEN'),
    'guvenilir-uye': ('Trusted Member', 'Email, phone and LinkedIn verified',
                      'Vertrauenswürdiges Mitglied', 'E-Mail, Telefon und LinkedIn verifiziert'),
    'dogrulanmis-akademisyen': ('Verified Academic', 'Academic identity verified – ALL PERMISSIONS',
                                'Verifizierte/r Wissenschaftler/in', 'Akademische Identität verifiziert – ALLE BERECHTIGUNGEN'),
    'istatistik-ustasi': ('Statistics Master', '50 correct answers in the Statistics category',
                          'Statistik-Profi', '50 richtige Antworten in der Kategorie Statistik'),
    'spss-uzmani': ('SPSS Expert', '50 correct answers in the SPSS category',
                    'SPSS-Experte/Expertin', '50 richtige Antworten in der Kategorie SPSS'),
    'python-ninja': ('Python Ninja', '50 correct answers in the Python category',
                     'Python-Ninja', '50 richtige Antworten in der Kategorie Python'),
    'r-ustadi': ('R Master', '50 correct answers in the R category',
                 'R-Meister/in', '50 richtige Antworten in der Kategorie R'),
    'quiz-efsanesi': ('Quiz Legend', '1,000 correct quiz answers in total – CAN SUBMIT PROPOSALS',
                      'Quiz-Legende', 'Insgesamt 1.000 richtige Quiz-Antworten – DARF ANGEBOTE ABGEBEN'),
}


def fill_translations(apps, schema_editor):
    Badge = apps.get_model('forum', 'Badge')
    for badge in Badge.objects.filter(slug__in=BADGE_TRANSLATIONS):
        name_en, desc_en, name_de, desc_de = BADGE_TRANSLATIONS[badge.slug]
        changed = []
        for field, value in (('name_en', name_en), ('description_en', desc_en),
                             ('name_de', name_de), ('description_de', desc_de)):
            if not getattr(badge, field):
                setattr(badge, field, value)
                changed.append(field)
        if changed:
            badge.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0155_rename_deleted_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='description_de',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Açıklama (DE)'),
        ),
        migrations.AddField(
            model_name='badge',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Açıklama (EN)'),
        ),
        migrations.AddField(
            model_name='badge',
            name='name_de',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Rozet Adı (DE)'),
        ),
        migrations.AddField(
            model_name='badge',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Rozet Adı (EN)'),
        ),
        # Geri alma: alanlar zaten kaldırılacağı için veri adımı no-op
        migrations.RunPython(fill_translations, migrations.RunPython.noop),
    ]
