# Generated by Django 5.2.16 on 2026-09-26 17:58

from django.db import migrations, models


# Canlı liste 26 Eylül 2026'da ölçüldü (43 kayıt); temizlik kullanıcı onaylı.
# Her adım id + beklenen başlık birlikte eşleşirse çalışır — farklı DB'de
# (yerel/Render) beklenmedik kayda dokunmaz.

# Birleştir: kaynak (id, eski başlık) → hedef id. İlan FK'si ve uzman
# yetenekleri hedefe taşınır, kaynak silinir.
MERGES = [
    (37, 'Yapay zeka modelleme', 3),
    (41, 'Ai modelleme', 3),
    (42, 'Yapay Zeka & ML, Python, Otomasyon', 3),
    (39, 'Python', 25),
    (35, 'Maxquda ile 27 kişiye ait verinin çalışılması', 23),
    (34, 'SPSS ve içerik analizi', 6),
]

# Ad düzeltme: id → (eski, yeni)
RENAMES = {
    3: ('Yapay zeka modellemeleri (Generative ai)', 'Yapay zekâ modelleme'),
    5: ('Makine öğrenmesi modlellemesi', 'Makine öğrenmesi modellemesi'),
    23: ('MAXQUDA ile nitel veri analizi', 'MAXQDA ile nitel veri analizi'),
    4: ('Eviews Analizleri', 'EViews analizleri'),
    36: ('Nitel Veri Analizi', 'Nitel veri analizi'),
    43: ('Makale Desteği', 'Makale desteği'),
}

# Pasife al (silinmez): kullanılmıyor + akademik analiz hizmeti dışı
DEACTIVATE = {
    31: 'C++', 32: 'Java', 33: 'Javascript',
    26: 'Google SEO hizmetleri', 27: 'Web sayfası tasarımı',
}

# Aktif kalan 32 kaydın çevirisi: id → (TR başlık, EN, DE)
TRANSLATIONS = {
    2: ('AMOS (Path analizi)', 'AMOS (Path Analysis)', 'AMOS (Pfadanalyse)'),
    3: ('Yapay zekâ modelleme', 'AI Modelling', 'KI-Modellierung'),
    4: ('EViews analizleri', 'EViews Analyses', 'EViews-Analysen'),
    5: ('Makine öğrenmesi modellemesi', 'Machine Learning Modelling', 'Machine-Learning-Modellierung'),
    6: ('SPSS ile veri analizi', 'Data Analysis with SPSS', 'Datenanalyse mit SPSS'),
    7: ('Akademik danışmanlık', 'Academic Consulting', 'Akademische Beratung'),
    8: ('NLP Modelleme', 'NLP Modelling', 'NLP-Modellierung'),
    9: ('Metin Editörlüğü', 'Text Editing', 'Lektorat'),
    10: ('Tez önerisi desteği', 'Thesis Proposal Support', 'Unterstützung beim Exposé'),
    11: ('Etik kurul desteği', 'Ethics Committee Support', 'Unterstützung beim Ethikantrag'),
    12: ('Excel analizleri', 'Excel Analyses', 'Excel-Analysen'),
    13: ('SmartPLS analizleri', 'SmartPLS Analyses', 'SmartPLS-Analysen'),
    14: ('Güç analizi (Power analizi)', 'Power Analysis', 'Poweranalyse'),
    15: ('Anket oluşturma desteği', 'Survey Design Support', 'Unterstützung bei der Fragebogenerstellung'),
    16: ('Tableau ile veri analizi', 'Data Analysis with Tableau', 'Datenanalyse mit Tableau'),
    17: ('PowerBI ile veri analizi', 'Data Analysis with Power BI', 'Datenanalyse mit Power BI'),
    18: ('R ile veri analizi', 'Data Analysis with R', 'Datenanalyse mit R'),
    19: ('Büyük veri analizi', 'Big Data Analysis', 'Big-Data-Analyse'),
    20: ('Zaman serisi analizleri', 'Time Series Analysis', 'Zeitreihenanalyse'),
    21: ('Stata ile veri analizi', 'Data Analysis with Stata', 'Datenanalyse mit Stata'),
    22: ('NVIVO ile nitel veri analizi', 'Qualitative Data Analysis with NVivo', 'Qualitative Datenanalyse mit NVivo'),
    23: ('MAXQDA ile nitel veri analizi', 'Qualitative Data Analysis with MAXQDA', 'Qualitative Datenanalyse mit MAXQDA'),
    24: ('MATLAB ile veri analizi', 'Data Analysis with MATLAB', 'Datenanalyse mit MATLAB'),
    25: ('Python ile veri analizi', 'Data Analysis with Python', 'Datenanalyse mit Python'),
    28: ('SQL ile veri yönetimi', 'Data Management with SQL', 'Datenmanagement mit SQL'),
    29: ('Geçerlik & güvenirlik analizleri', 'Validity & Reliability Analyses', 'Validitäts- & Reliabilitätsanalysen'),
    30: ('Faktör analizi', 'Factor Analysis', 'Faktorenanalyse'),
    36: ('Nitel veri analizi', 'Qualitative Data Analysis', 'Qualitative Datenanalyse'),
    38: ('Veri etiketleme', 'Data Labelling', 'Datenannotation'),
    40: ('Python eğitimi', 'Python Training', 'Python-Schulung'),
    43: ('Makale desteği', 'Article Support', 'Unterstützung bei Fachartikeln'),
    44: ('Tez danışmanlığı', 'Thesis Consulting', 'Beratung bei Abschlussarbeiten'),
}


def cleanup_and_translate(apps, schema_editor):
    JobCategory = apps.get_model('forum', 'JobCategory')
    FreelanceJob = apps.get_model('forum', 'FreelanceJob')
    Profile = apps.get_model('forum', 'Profile')
    Skills = Profile.skills.through

    for src_id, src_title, dst_id in MERGES:
        src = JobCategory.objects.filter(pk=src_id, title=src_title).first()
        if src is None or not JobCategory.objects.filter(pk=dst_id).exists():
            continue
        FreelanceJob.objects.filter(category_id=src_id).update(category_id=dst_id)
        has_dst = set(Skills.objects.filter(jobcategory_id=dst_id).values_list('profile_id', flat=True))
        Skills.objects.filter(jobcategory_id=src_id, profile_id__in=has_dst).delete()
        Skills.objects.filter(jobcategory_id=src_id).update(jobcategory_id=dst_id)
        src.delete()

    for pk, (old, new) in RENAMES.items():
        JobCategory.objects.filter(pk=pk, title=old).update(title=new)

    for pk, title in DEACTIVATE.items():
        JobCategory.objects.filter(pk=pk, title=title).update(is_active=False)

    for pk, (tr, en, de) in TRANSLATIONS.items():
        JobCategory.objects.filter(pk=pk, title=tr, title_en='').update(title_en=en)
        JobCategory.objects.filter(pk=pk, title=tr, title_de='').update(title_de=de)


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0156_badge_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='title_de',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Kategori Adı (DE)'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Kategori Adı (EN)'),
        ),
        # Geri alma: birleştirme/silme veri düzeyinde geri döndürülmez (no-op);
        # geri almak gerekirse deploy öncesi DB yedeği esas alınır.
        migrations.RunPython(cleanup_and_translate, migrations.RunPython.noop),
    ]
