# Generated by Django 5.2.16 on 2026-09-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0157_jobcategory_translations_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='language',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Dil'),
        ),
    ]
