# Generated by Django 5.2.16 on 2026-09-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0158_projectrequest_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='source',
            field=models.CharField(blank=True, choices=[('direct', 'Doğrudan Form'), ('yoktez', 'YÖK Tez'), ('trdizin', 'TR Dizin'), ('tool', 'Analiz Aracı'), ('hero', 'Ana Sayfa Hero'), ('home_corporate', 'Ana Sayfa Kurumsal'), ('verification', 'AI Doğrulama Bandı'), ('agentic', 'AI Çözümler Sayfası'), ('tableau', 'Tableau Sayfası'), ('bibliometrics', 'Bibliometri Sayfası'), ('analiz_triyaj', 'Analiz Araçları Triyaj'), ('nav', 'Navbar'), ('footer', 'Footer'), ('home_market', 'Ana Sayfa Pazar Kartı'), ('home_steps', 'Ana Sayfa Nasıl Çalışır'), ('home_faq', 'Ana Sayfa SSS'), ('market_page', 'Pazar Yeri Sayfası')], default='direct', max_length=20, verbose_name='Kaynak'),
        ),
    ]
