# Generated by Django 5.2.17 on 2026-09-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0159_projectrequest_source_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feature_pubmed',
            field=models.BooleanField(default=False, help_text='Varsayılan kapalı — NCBI_API_KEY eklenip canlıda denendikten sonra açın (anahtarsız da çalışır, 3 istek/sn).', verbose_name='PubMed Yayın Tarama'),
        ),
    ]
