# Generated by Django 5.2.17 on 2026-09-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0160_sitesettings_feature_pubmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='promote_price_3_days',
            field=models.PositiveIntegerField(default=250, verbose_name='İlan vitrini: 3 gün (TL)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promote_price_7_days',
            field=models.PositiveIntegerField(default=400, verbose_name='İlan vitrini: 7 gün (TL)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='scrape_price_first_100',
            field=models.PositiveIntegerField(default=250, help_text='OpenAlex, Semantic Scholar, TR Dizin ve OAI-PMH siparişleri. Yeni siparişlere uygulanır; mevcut siparişlerin tutarı değişmez.', verbose_name='Tarama siparişi: ilk 100 kayıt (TL)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='scrape_price_per_100',
            field=models.PositiveIntegerField(default=100, verbose_name='Tarama siparişi: sonraki her 100 kayıt (TL)'),
        ),
    ]
