# Generated by Django 5.2.17 on 2026-10-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0164_jobcategory_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='job_weekly_limit_free',
            field=models.PositiveIntegerField(default=2, verbose_name='Haftalık ilan hakkı: normal kullanıcı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='job_weekly_limit_premium',
            field=models.PositiveIntegerField(default=5, verbose_name='Haftalık ilan hakkı: Premium'),
        ),
    ]
