# Generated by Django 5.2.17 on 2026-10-02 07:48

from django.db import migrations, models
from django.db.models import F


def mevcut_ilanlar_yayinda(apps, schema_editor):
    """Onay sistemi öncesi açılan ilanlar zaten yayındaydı: approved_at = created_at.

    Boş kalırsa açık ilan sonraki save()'de yeniden 'yayına alınır' (süre + ilk ilan hediyesi sıfırlanır).
    Yalnız boş alanlara yazar.
    """
    FreelanceJob = apps.get_model('forum', 'FreelanceJob')
    FreelanceJob.objects.filter(approved_at__isnull=True).update(approved_at=F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0165_sitesettings_job_weekly_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancejob',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yayına Alınma Tarihi'),
        ),
        migrations.AddField(
            model_name='freelancejob',
            name='rejection_note',
            field=models.TextField(blank=True, help_text='İsteğe bağlı; ilan sahibine e-postada gönderilir.', verbose_name='Ret Notu'),
        ),
        migrations.AddField(
            model_name='freelancejob',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('service_ad', 'Hizmet tanıtımı — iş talebi değil'), ('incomplete', 'Eksik veya anlaşılmaz içerik'), ('rules', 'Platform kurallarına aykırı')], max_length=20, verbose_name='Ret Gerekçesi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='job_approval_required',
            field=models.BooleanField(default=True, help_text="Açıkken yeni ilan 'Onay Bekliyor' durumunda açılır; admin onaylayınca yayınlanır ve sahibine e-posta gider.", verbose_name='İlan yayını admin onayına bağlı'),
        ),
        migrations.AlterField(
            model_name='freelancejob',
            name='status',
            field=models.CharField(choices=[('pending', 'Onay Bekliyor'), ('open', 'Açık (Teklif Bekliyor)'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi'), ('rejected', 'Reddedildi')], default='open', max_length=20, verbose_name='Durum'),
        ),
        migrations.RunPython(mevcut_ilanlar_yayinda, migrations.RunPython.noop),
    ]
