# Generated by Django 5.2.17 on 2026-10-02 09:02

from django.db import migrations, models


def bekleyen_bagislara_gun_yaz(apps, schema_editor):
    """Onay bekleyen bağışlara söz verilen günü yaz: talep edilen katman (conversation_id 'TIER-<pk>'), yoksa tutara uyan katman.

    Yalnız boş (0) alanlara yazar; tamamlanmış bağışlara dokunmaz.
    """
    Donation = apps.get_model('forum', 'Donation')
    DonationTier = apps.get_model('forum', 'DonationTier')
    for d in Donation.objects.filter(status__in=('pending', 'pending_confirmation'), premium_days_promised=0):
        tier = None
        if (d.conversation_id or '').startswith('TIER-'):
            tier = DonationTier.objects.filter(pk=d.conversation_id[5:]).first() if d.conversation_id[5:].isdigit() else None
        if tier is None:
            tier = DonationTier.objects.filter(is_active=True, min_amount__lte=d.amount).order_by('-min_amount').first()
        if tier:
            d.premium_days_promised = tier.premium_days
            d.save(update_fields=['premium_days_promised'])


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0166_freelancejob_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='premium_days_promised',
            field=models.IntegerField(default=0, help_text='Bağış talep edildiğinde seçilen katmanın gün sayısı; onayda bu süre verilir.', verbose_name='Söz Verilen Premium Gün'),
        ),
        migrations.RunPython(bekleyen_bagislara_gun_yaz, migrations.RunPython.noop),
    ]
