# Generated by Django 5.2.17 on 2026-10-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0167_donation_premium_days_promised'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='job_description_max_chars',
            field=models.PositiveIntegerField(default=1500, help_text='Yeni ilan ve ilan düzenlemede uygulanır; mevcut ilanlar değişmez.', verbose_name='İlan açıklaması: en fazla karakter'),
        ),
    ]
