# Generated by Django 5.2.17 on 2026-10-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0168_sitesettings_job_description_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='job_title_max_chars',
            field=models.PositiveIntegerField(default=80, help_text='Yeni ilan ve ilan düzenlemede uygulanır (en fazla 200); mevcut ilanlar değişmez.', verbose_name='İlan başlığı: en fazla karakter'),
        ),
    ]
