# Generated by Django 5.2.9 on 2026-10-04 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0169_sitesettings_job_title_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=150, verbose_name='Başlık (H1)')),
                ('meta_title', models.CharField(blank=True, default='', max_length=70, verbose_name='SEO Başlığı')),
                ('meta_description', models.CharField(blank=True, default='', max_length=160, verbose_name='SEO Açıklaması')),
                ('intro', models.TextField(verbose_name='Giriş (vaat)')),
                ('process_text', models.TextField(blank=True, default='', verbose_name='Süreç')),
                ('ethics_text', models.TextField(blank=True, default='', verbose_name='Etik sınırlar')),
                ('is_active', models.BooleanField(default=False, verbose_name='Yayında')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Hizmet Sayfası',
                'verbose_name_plural': 'Hizmet Sayfaları',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_hizmet_sayfalari',
            field=models.BooleanField(default=False, help_text='Kapalıyken /hizmetler/ 404 döner. Pilot: önce yalnız Nicel Analiz sayfasını ServicePage.is_active ile açın.', verbose_name='Hizmet Sayfaları (/hizmetler/)'),
        ),
        migrations.CreateModel(
            name='ServicePageFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Soru')),
                ('answer', models.TextField(verbose_name='Cevap')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='forum.servicepage')),
            ],
            options={
                'verbose_name': 'Hizmet Sayfası SSS',
                'verbose_name_plural': 'Hizmet Sayfası SSS',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor', models.SlugField(verbose_name='Çapa (#anchor)')),
                ('title', models.CharField(max_length=120, verbose_name='Başlık')),
                ('body', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('related_job_categories', models.ManyToManyField(blank=True, to='forum.jobcategory', verbose_name='İlgili iş kategorileri')),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='forum.servicepage')),
            ],
            options={
                'verbose_name': 'Hizmet Sayfası Bölümü',
                'verbose_name_plural': 'Hizmet Sayfası Bölümleri',
                'ordering': ['order'],
            },
        ),
    ]
