# Generated by Django 5.2.17 on 2026-10-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0174_badge_profili_tamamladi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='directory_override',
            field=models.BooleanField(blank=True, default=None, help_text='Boş = otomatik kural (puan + en az 3 uzmanlık alanı + e-posta doğrulama; admin/staff hesapları otomatik dışarıda kalır). İşaretli (Evet) = kurala bakılmaksızın dizine girer. İşaretli değil (Hayır) = kurala bakılmaksızın dizinde hiç görünmez.', null=True, verbose_name='Uzman Dizini: Zorla Göster/Gizle'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='uzman_dizini_min_puan',
            field=models.PositiveIntegerField(default=200, help_text='Dizine girmek için gereken en az akademik puan (reputation). Ayrıca en az 3 uzmanlık alanı seçili ve e-posta doğrulanmış olmalı; admin/staff hesapları varsayılan dışarıda kalır (Profile.directory_override ile tekil istisna yapılabilir).', verbose_name='Uzman Dizini: minimum puan'),
        ),
    ]
