# Generated by Django 5.2.9 on 2026-03-04 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yoktez', '0002_ensure_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TezAnaliz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tez_ad', models.CharField(blank=True, max_length=300)),
                ('yazar', models.CharField(blank=True, max_length=200)),
                ('universite', models.CharField(blank=True, max_length=200)),
                ('tur', models.CharField(blank=True, max_length=10)),
                ('yil_baslangic', models.IntegerField(blank=True, null=True)),
                ('yil_bitis', models.IntegerField(blank=True, null=True)),
                ('metin', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('records', models.JSONField(blank=True, default=list)),
                ('analysis_data', models.JSONField(blank=True, default=dict)),
                ('pdf_url', models.URLField(blank=True, default='', max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tez_analizler', to=settings.AUTH_USER_MODEL)),
                ('yok_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analizler', to='yoktez.yoktezsearchjob')),
            ],
            options={
                'verbose_name': 'Tez Analizi',
                'verbose_name_plural': 'Tez Analizleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
