# Generated by Django 5.2.9 on 2026-03-04 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliometrics', '0002_add_source_alex_job'),
        ('makaleanaliz', '0001_initial'),
        ('tezanaliz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliometricJobProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Bibliometrik Analiz İşi',
                'verbose_name_plural': 'Bibliometrik Analiz İşleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bibliometrics.bibliometricjob',),
        ),
        migrations.CreateModel(
            name='BibliometricOrderProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Bibliometrik Sipariş',
                'verbose_name_plural': 'Bibliometrik Siparişler',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bibliometrics.bibliometricorder',),
        ),
        migrations.CreateModel(
            name='MakaleAnalizProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Makale Analizi',
                'verbose_name_plural': 'Makale Analizleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('makaleanaliz.makaleanaliz',),
        ),
    ]
