# Generated by Django 5.2.9 on 2026-02-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrdizinArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trdizin_id', models.CharField(max_length=100, unique=True, verbose_name='TR Dizin ID')),
                ('title', models.TextField(verbose_name='Başlık')),
                ('authors', models.JSONField(default=list, verbose_name='Yazarlar')),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yayın Yılı')),
                ('journal', models.CharField(blank=True, max_length=500, verbose_name='Dergi')),
                ('abstract', models.TextField(blank=True, verbose_name='Özet')),
                ('keywords', models.JSONField(default=list, verbose_name='Anahtar Kelimeler')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='Çekilme Tarihi')),
            ],
            options={
                'verbose_name': 'TR Dizin Makalesi',
                'verbose_name_plural': 'TR Dizin Makaleleri',
                'ordering': ['-publication_year'],
            },
        ),
    ]
