# Generated by Django 5.2.9 on 2026-05-18 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makaleanaliz', '0001_initial'),
        ('oaipmh', '0006_oaipmhorder_oaipmh_oaip_status_ddad4e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makaleanaliz',
            name='oai_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analizler', to='oaipmh.oaipmhsearchjob'),
        ),
    ]
