# Generated by Django 5.2.17 on 2026-09-29 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PubMedSearchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_parts', models.JSONField(default=list, verbose_name='Sorgu Parçaları')),
                ('api_query', models.TextField(blank=True, verbose_name='Oluşturulan PubMed Sorgusu')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20)),
                ('total_results', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('demo_results', models.JSONField(blank=True, default=list)),
                ('all_results', models.JSONField(blank=True, default=list)),
                ('demo_file_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Demo Dosya URL (S3)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('demo_email_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubmed_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PubMed Arama (Demo)',
                'verbose_name_plural': 'PubMed Aramaları (Demo)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='pubmed_pubm_status_99fe1b_idx'), models.Index(fields=['created_at'], name='pubmed_pubm_created_04b536_idx')],
            },
        ),
    ]
