# Generated by Django 5.2.9 on 2026-02-19 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Üniversite Adı')),
                ('domain', models.CharField(max_length=100, verbose_name='Domain')),
                ('oai_url', models.URLField(verbose_name='OAI-PMH URL')),
                ('repo_name', models.CharField(blank=True, max_length=200, verbose_name='Repo Adı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Üniversite',
                'verbose_name_plural': 'Üniversiteler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OAIPMHSearchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_type', models.CharField(choices=[('keyword', 'Anahtar Kelime Araması'), ('browse', 'Üniversite Tez Taraması')], default='keyword', max_length=10)),
                ('keyword', models.CharField(blank=True, max_length=300, verbose_name='Anahtar Kelime')),
                ('year_from', models.IntegerField(blank=True, null=True, verbose_name='Başlangıç Yılı')),
                ('year_to', models.IntegerField(blank=True, null=True, verbose_name='Bitiş Yılı')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20)),
                ('total_results', models.PositiveIntegerField(default=0)),
                ('demo_results', models.JSONField(default=list)),
                ('all_results', models.JSONField(default=list)),
                ('demo_file_url', models.URLField(blank=True)),
                ('all_results_file_url', models.URLField(blank=True)),
                ('demo_email_sent', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oaipmh_jobs', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='browse_jobs', to='oaipmh.university', verbose_name='Üniversite')),
            ],
            options={
                'verbose_name': 'Arama İşi',
                'verbose_name_plural': 'Arama İşleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OAIPMHOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abstract_count', models.PositiveIntegerField(verbose_name='İstenen Kayıt Sayısı')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Fiyat (TL)')),
                ('status', models.CharField(choices=[('pending_payment', 'Ödeme Bekleniyor'), ('payment_review', 'Ödeme İncelemede'), ('approved', 'Onaylandı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='pending_payment', max_length=20)),
                ('payment_note', models.TextField(blank=True, verbose_name='Ödeme Notu')),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin Notu')),
                ('results_email_sent', models.BooleanField(default=False)),
                ('results_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oaipmh_orders', to=settings.AUTH_USER_MODEL)),
                ('search_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='oaipmh.oaipmhsearchjob')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-created_at'],
            },
        ),
    ]
