# Generated by Django 5.2.9 on 2026-02-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaipmh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oaipmhsearchjob',
            name='abstract_query',
            field=models.CharField(blank=True, max_length=300, verbose_name='Özet Filtresi'),
        ),
        migrations.AddField(
            model_name='oaipmhsearchjob',
            name='university_ids',
            field=models.JSONField(blank=True, default=list, verbose_name="Seçili Üniversite ID'leri"),
        ),
        migrations.AlterField(
            model_name='oaipmhsearchjob',
            name='keyword',
            field=models.CharField(blank=True, max_length=300, verbose_name='Başlık Filtresi'),
        ),
    ]
