# Generated by Django 5.2.9 on 2026-03-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaipmh', '0003_load_universities'),
        ('openalex', '0001_initial'),
        ('trdizin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlexSearchJobProxy',
            fields=[
            ],
            options={
                'verbose_name': 'OpenAlex Arama İşi',
                'verbose_name_plural': 'OpenAlex Arama İşleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('openalex.alexsearchjob',),
        ),
        migrations.CreateModel(
            name='DizinSearchJobProxy',
            fields=[
            ],
            options={
                'verbose_name': 'TR Dizin Arama İşi',
                'verbose_name_plural': 'TR Dizin Arama İşleri',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trdizin.dizinsearchjob',),
        ),
    ]
