# Generated by Django 5.2.9 on 2026-03-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaipmh', '0004_alexsearchjobproxy_dizinsearchjobproxy'),
        ('yoktez', '0002_ensure_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='YokTezSearchJobProxy',
            fields=[
            ],
            options={
                'verbose_name': 'YÖK Tez Araması',
                'verbose_name_plural': 'YÖK Tez Aramaları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('yoktez.yoktezsearchjob',),
        ),
    ]
