# Generated by Django 5.2.9 on 2026-03-12 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaipmh', '0005_yoktez_proxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='oaipmhorder',
            index=models.Index(fields=['status'], name='oaipmh_oaip_status_ddad4e_idx'),
        ),
        migrations.AddIndex(
            model_name='oaipmhorder',
            index=models.Index(fields=['created_at'], name='oaipmh_oaip_created_f48d62_idx'),
        ),
        migrations.AddIndex(
            model_name='oaipmhsearchjob',
            index=models.Index(fields=['status'], name='oaipmh_oaip_status_08734f_idx'),
        ),
        migrations.AddIndex(
            model_name='oaipmhsearchjob',
            index=models.Index(fields=['created_at'], name='oaipmh_oaip_created_7e10cd_idx'),
        ),
    ]
