# Generated by Django 5.2.9 on 2026-05-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semanticscholar', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='semanticorder',
            new_name='semanticsch_status_92943d_idx',
            old_name='semanticord_status_idx',
        ),
        migrations.RenameIndex(
            model_name='semanticorder',
            new_name='semanticsch_created_745d9c_idx',
            old_name='semanticord_created_idx',
        ),
        migrations.RenameIndex(
            model_name='semanticsearchjob',
            new_name='semanticsch_status_c632c1_idx',
            old_name='semanticsch_status_idx',
        ),
        migrations.RenameIndex(
            model_name='semanticsearchjob',
            new_name='semanticsch_created_8dde35_idx',
            old_name='semanticsch_created_idx',
        ),
    ]
