# Generated by Django 5.2.9 on 2026-06-19 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_minutes_admin', models.PositiveIntegerField(default=120, help_text='Admin/staff kullanıcılar için izin verilen maksimum video süresi (dakika). Standart kullanıcılar bu değerin yarısını kullanabilir.', verbose_name='Admin maksimum dakika')),
            ],
            options={
                'verbose_name': 'Transcript Ayarları',
                'verbose_name_plural': 'Transcript Ayarları',
            },
        ),
        migrations.CreateModel(
            name='TranscriptJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(verbose_name='Video URL')),
                ('video_id', models.CharField(blank=True, max_length=64)),
                ('video_title', models.CharField(blank=True, max_length=512)),
                ('video_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('language_requested', models.CharField(blank=True, help_text='Boşsa otomatik seçilir', max_length=10)),
                ('language_used', models.CharField(blank=True, max_length=10)),
                ('translated', models.BooleanField(default=False)),
                ('delivery', models.CharField(choices=[('download', 'İndir (TXT)'), ('email', 'E-posta ile gönder')], default='download', max_length=20)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('transcript_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Hata')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transcript İşi',
                'verbose_name_plural': 'Transcript İşleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
