# Generated by Django 5.2.9 on 2026-06-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptsettings',
            name='whisper_model',
            field=models.CharField(choices=[('tiny', 'Tiny — en hızlı, az bellek (~390MB)'), ('base', 'Base — hızlı, iyi doğruluk (~500MB)'), ('small', 'Small — dengeli (~1GB) ✓ Önerilen'), ('medium', 'Medium — yüksek doğruluk (~2.5GB)'), ('large-v3', 'Large v3 — en iyi doğruluk (~4GB)')], default='small', help_text="Büyük model = daha doğru ama daha yavaş ve fazla bellek. Sunucu RAM'ine göre seçin.", max_length=20, verbose_name='Whisper model boyutu'),
        ),
    ]
