# Generated by Django 5.2.9 on 2026-06-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0002_transcriptsettings_whisper_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptsettings',
            name='whisper_model',
        ),
    ]
