# Generated by Django 5.2.9 on 2026-03-14 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IstatistikJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool', models.CharField(choices=[('cronbach', 'Güvenilirlik Analizi (Cronbach Alpha)'), ('normallik', 'Normallik Testi'), ('betimsel', 'Betimleyici İstatistik')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Hata')], default='pending', max_length=20)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='istatistik_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İstatistik İş',
                'verbose_name_plural': 'İstatistik İşler',
                'ordering': ['-created_at'],
            },
        ),
    ]
