# Generated by Django 5.2.9 on 2026-04-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istatistik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='istatistikjob',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='istatistikjob',
            name='tool',
            field=models.CharField(choices=[('cronbach', 'Güvenilirlik Analizi (Cronbach Alpha)'), ('normallik', 'Normallik Testi'), ('betimsel', 'Betimleyici İstatistik'), ('korelasyon', 'Korelasyon Matrisi')], max_length=20),
        ),
    ]
