# Generated by Django 5.2.9 on 2026-04-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istatistik', '0002_add_korelasyon_tool_and_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istatistikjob',
            name='tool',
            field=models.CharField(choices=[('cronbach', 'Güvenilirlik Analizi (Cronbach Alpha)'), ('normallik', 'Normallik Testi'), ('betimsel', 'Betimleyici İstatistik'), ('korelasyon', 'Korelasyon Matrisi'), ('ttesti', 't-Testi'), ('anova', 'Tek Yönlü ANOVA')], max_length=20),
        ),
    ]
