# Generated by Django 5.2.9 on 2026-05-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istatistik', '0007_add_regression_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istatistikjob',
            name='tool',
            field=models.CharField(choices=[('cronbach', 'Güvenilirlik Analizi (Cronbach Alpha)'), ('normallik', 'Normallik Testi'), ('betimsel', 'Betimleyici İstatistik'), ('korelasyon', 'Korelasyon Matrisi'), ('ttesti', 't-Testi'), ('anova', 'Tek Yönlü ANOVA'), ('mann_whitney', 'Mann-Whitney U Testi'), ('kruskal_wallis', 'Kruskal-Wallis H Testi'), ('ki_kare', 'Ki-Kare Testi'), ('lineer_regresyon', 'Çoklu Doğrusal Regresyon'), ('lojistik_regresyon', 'Lojistik Regresyon'), ('afa', 'Açıklayıcı Faktör Analizi (AFA)'), ('wilcoxon', 'Wilcoxon İşaret Testi')], max_length=20),
        ),
    ]
