# Generated by Django 5.2.9 on 2026-03-03 18:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YokTezSearchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tez_ad', models.CharField(blank=True, max_length=300, verbose_name='Tez Adı')),
                ('yazar', models.CharField(blank=True, max_length=200, verbose_name='Yazar')),
                ('danisman', models.CharField(blank=True, max_length=200, verbose_name='Danışman')),
                ('universite', models.CharField(blank=True, max_length=200, verbose_name='Üniversite')),
                ('tur', models.CharField(blank=True, max_length=10, verbose_name='Tez Türü')),
                ('yil_baslangic', models.IntegerField(blank=True, null=True, verbose_name='Başlangıç Yılı')),
                ('yil_bitis', models.IntegerField(blank=True, null=True, verbose_name='Bitiş Yılı')),
                ('metin', models.CharField(blank=True, max_length=300, verbose_name='Özet/Metin')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20)),
                ('total_results', models.IntegerField(default=0)),
                ('demo_results', models.JSONField(blank=True, default=list)),
                ('all_results_file_url', models.URLField(blank=True, default='', max_length=500)),
                ('demo_email_sent', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yoktez_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'YÖK Tez Araması',
                'verbose_name_plural': 'YÖK Tez Aramaları',
                'ordering': ['-created_at'],
            },
        ),
    ]
