# Generated by Django 5.2.9 on 2026-02-06 11:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TezSearchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('konu', models.CharField(max_length=200, verbose_name='Bilim Alanı')),
                ('keywords', models.JSONField(default=list, verbose_name='Anahtar Kelimeler')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20)),
                ('total_results', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('demo_results', models.JSONField(blank=True, default=list)),
                ('all_results', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('demo_email_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tez_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tez Arama (Demo)',
                'verbose_name_plural': 'Tez Aramaları (Demo)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TezOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abstract_count', models.PositiveIntegerField(verbose_name='İstenen Abstract Sayısı')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Tutar (TL)')),
                ('status', models.CharField(choices=[('pending_payment', 'Ödeme Bekleniyor'), ('payment_review', 'Ödeme İnceleniyor'), ('approved', 'Onaylandı'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı - Gönderildi'), ('cancelled', 'İptal')], default='pending_payment', max_length=20)),
                ('payment_note', models.TextField(blank=True, verbose_name='Ödeme Açıklaması')),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin Notu')),
                ('results_email_sent', models.BooleanField(default=False)),
                ('results_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tez_orders', to=settings.AUTH_USER_MODEL)),
                ('search_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='yoktez.tezsearchjob')),
            ],
            options={
                'verbose_name': 'Tez Siparişi',
                'verbose_name_plural': 'Tez Siparişleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
