# Generated by Django 5.2.9 on 2026-02-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoktez', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tezsearchjob',
            name='demo_file_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Demo Dosya URL (S3)'),
        ),
    ]
