# Generated by Django 5.2.9 on 2026-03-12 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoktez', '0003_add_all_results'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='yoktezsearchjob',
            index=models.Index(fields=['status'], name='yoktez_yokt_status_ea2530_idx'),
        ),
        migrations.AddIndex(
            model_name='yoktezsearchjob',
            index=models.Index(fields=['created_at'], name='yoktez_yokt_created_9c3ecc_idx'),
        ),
    ]
